# Generated by Django 3.2.9 on 2021-12-09 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('semester', models.CharField(max_length=2)),
                ('phone', models.CharField(max_length=13)),
                ('email', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Users',
            },
        ),
    ]
