# Generated by Django 3.2.9 on 2021-12-10 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendence', '0003_alter_user_days_present'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='days_present',
        ),
    ]
